### ISSUE TITLE
'Residual' is not defined

### ISSUE THREAD

**Issue by 112299aa** [wurenkai/HSH-UNet#1]
Hello, the code is reporting NameError: name 'Residual' is not defined. May I ask if you did not import some bags, there is Residual in the bags

**Comment by wurenkai** [comment]
Hi. Thank you for asking this question. We did miss this definition when we uploaded the code. We have re-added it to the model.py file. Or you can add to the model.py file as follows:
```
class Residual(nn.Module):
    def __init__(self, fn):
        super().__init__()
        self.fn = fn

    def forward(self, x):
        return self.fn(x) + x
```
